//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidoclu.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vidoclu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _000 {
            get {
                object obj = ResourceManager.GetObject("_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _001 {
            get {
                object obj = ResourceManager.GetObject("_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _002 {
            get {
                object obj = ResourceManager.GetObject("_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _003 {
            get {
                object obj = ResourceManager.GetObject("_003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _004 {
            get {
                object obj = ResourceManager.GetObject("_004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _005 {
            get {
                object obj = ResourceManager.GetObject("_005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _006 {
            get {
                object obj = ResourceManager.GetObject("_006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _007 {
            get {
                object obj = ResourceManager.GetObject("_007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _008 {
            get {
                object obj = ResourceManager.GetObject("_008", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _009 {
            get {
                object obj = ResourceManager.GetObject("_009", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _010 {
            get {
                object obj = ResourceManager.GetObject("_010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _011 {
            get {
                object obj = ResourceManager.GetObject("_011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _012 {
            get {
                object obj = ResourceManager.GetObject("_012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _013 {
            get {
                object obj = ResourceManager.GetObject("_013", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _014 {
            get {
                object obj = ResourceManager.GetObject("_014", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _015 {
            get {
                object obj = ResourceManager.GetObject("_015", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;style.css&quot; /&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;div id=&quot;contenedor&quot;&gt;
        ///			&lt;br&gt;&lt;br&gt;
        ///			&lt;p&gt;
        ///				&lt;h1&gt;Vidocl&amp;uacute; - Ayuda&lt;/h1&gt;
        ///			&lt;/p&gt;
        ///			&lt;p&gt;&lt;a href=&quot;./index.html&quot;&gt;(Atr&amp;aacute;s)&lt;/a&gt;&lt;/p&gt;
        ///			&lt;p&gt;
        ///				---------------------------------------
        ///			&lt;/p&gt;
        ///			&lt;p&gt;
        ///				&lt;h2&gt;Vidocl&amp;uacute; - &lt;a href=&quot;http://proyectsource.tk&quot;&gt;Proyect Source&lt;/a&gt;&lt;/h2&gt;
        ///			&lt;/p&gt;
        ///			&lt;p&gt;
        ///				&lt;h3&gt;(&lt;a href=&quot;mailto:batkiel@gmail.com&quot;&gt;Email de Contacto&lt;/a&gt;)&lt;/h2&gt;
        ///			&lt;/p&gt;
        ///			&lt;img src=&quot;./img/015.png&quot;/&gt;
        ///			&lt;p&gt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap arrow_left {
            get {
                object obj = ResourceManager.GetObject("arrow_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_right {
            get {
                object obj = ResourceManager.GetObject("arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap browseIcon {
            get {
                object obj = ResourceManager.GetObject("browseIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap default_image {
            get {
                object obj = ResourceManager.GetObject("default_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;style.css&quot; /&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;div id=&quot;contenedor&quot;&gt;
        ///			&lt;br&gt;&lt;br&gt;
        ///			&lt;p&gt;
        ///				&lt;h1&gt;Vidocl&amp;uacute; - Ayuda&lt;/h1&gt;
        ///			&lt;/p&gt;
        ///			&lt;p&gt;&lt;a href=&quot;./index.html&quot;&gt;(Atr&amp;aacute;s)&lt;/a&gt;&lt;/p&gt;
        ///			&lt;p&gt;
        ///				&lt;h2&gt;&lt;a href=&quot;#AddUser&quot;&gt;Agregando&lt;/a&gt;, &lt;a href=&quot;#ModUser&quot;&gt;Editando&lt;/a&gt; y &lt;a href=&quot;#DelUser&quot;&gt;Borrando&lt;/a&gt; Peliculas&lt;/h2&gt;
        ///			&lt;/p&gt;
        ///			&lt;a name=&quot;AddUser&quot; id=&quot;addUser&quot;&gt;&lt;/a&gt;
        ///			&lt;p&gt;
        ///				Agregar una pelicula es muy sencillo. Primero debemos pulsar el bot&amp;oacute;n &quot;Peliculas&quot;
        ///			 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string films {
            get {
                return ResourceManager.GetString("films", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon icono {
            get {
                object obj = ResourceManager.GetObject("icono", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;style.css&quot; /&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;div id=&quot;contenedor&quot;&gt;
        ///			&lt;br&gt;&lt;br&gt;
        ///			&lt;p&gt;
        ///				&lt;h1&gt;Vidocl&amp;uacute; - Ayuda&lt;/h1&gt;
        ///			&lt;/p&gt;
        ///			&lt;p&gt;
        ///				---------------------------------------
        ///			&lt;/p&gt;
        ///			&lt;p&gt;
        ///				&lt;h2&gt;&lt;a href=&quot;./users.html&quot;&gt;Agregando, Editando y Borrando Usuarios&lt;/a&gt;&lt;/h2&gt;
        ///			&lt;/p&gt;
        ///			&lt;p&gt;
        ///				&lt;h2&gt;&lt;a href=&quot;./films.html&quot;&gt;Agregando, Editando y Borrando Peliculas&lt;/a&gt;&lt;/h2&gt;
        ///			&lt;/p&gt;
        ///			&lt;p&gt;
        ///				&lt;h2&gt;&lt;a href=&quot;./rent.html&quot;&gt;Alquilando y Devolviendo Peliculas&lt;/a&gt;&lt;/h2&gt;
        ///	 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;style.css&quot; /&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;div id=&quot;contenedor&quot;&gt;
        ///			&lt;br&gt;&lt;br&gt;
        ///			&lt;p&gt;
        ///				&lt;h1&gt;Vidocl&amp;uacute; - Ayuda&lt;/h1&gt;
        ///			&lt;/p&gt;
        ///			&lt;p&gt;&lt;a href=&quot;./index.html&quot;&gt;(Atr&amp;aacute;s)&lt;/a&gt;&lt;/p&gt;
        ///			&lt;p&gt;
        ///				&lt;h2&gt;&lt;a href=&quot;#AddUser&quot;&gt;Alquilando&lt;/a&gt; y &lt;a href=&quot;#ModUser&quot;&gt;Devolviendo&lt;/a&gt; una Pelicula&lt;/h2&gt;
        ///			&lt;/p&gt;
        ///			&lt;a name=&quot;AddUser&quot; id=&quot;addUser&quot;&gt;&lt;/a&gt;
        ///			&lt;p&gt;
        ///				Alquilar una pelicula es muy sencillo. Primero debemos pulsar el bot&amp;oacute;n &quot;Alquilar&quot;
        ///				en el men&amp;uacute; princip [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string rent {
            get {
                return ResourceManager.GetString("rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /* Aitor González Fernández */
        ///
        ////* Estilos basicos */
        ///
        ///body {
        ///  background-color: #d8d0e1;
        ///  font: 70%/160% &quot;verdana&quot;, sans-serif;
        ///  color: #192666;
        ///  padding: 0px;
        ///}
        ///
        ////* Cuerpo del HTML */
        /// 
        ///#contenedor {
        ///  width:770px;
        ///  margin-left: auto;
        ///  margin-right: auto;
        ///  text-align: center;
        ///}
        ///
        ///p, h1, h2 {
        ///	text-align: center;
        ///}
        ///
        ///img {
        ///	align: center;
        ///}
        ///.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;style.css&quot; /&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;div id=&quot;contenedor&quot;&gt;
        ///			&lt;br&gt;&lt;br&gt;
        ///			&lt;p&gt;
        ///				&lt;h1&gt;Vidocl&amp;uacute; - Ayuda&lt;/h1&gt;
        ///			&lt;/p&gt;
        ///			&lt;p&gt;&lt;a href=&quot;./index.html&quot;&gt;(Atr&amp;aacute;s)&lt;/a&gt;&lt;/p&gt;
        ///			&lt;p&gt;
        ///				&lt;h2&gt;&lt;a href=&quot;#AddUser&quot;&gt;Agregando&lt;/a&gt;, &lt;a href=&quot;#ModUser&quot;&gt;Editando&lt;/a&gt; y &lt;a href=&quot;#DelUser&quot;&gt;Borrando&lt;/a&gt; Usuarios&lt;/h2&gt;
        ///			&lt;/p&gt;
        ///			&lt;a name=&quot;AddUser&quot; id=&quot;addUser&quot;&gt;&lt;/a&gt;
        ///			&lt;p&gt;
        ///				Agregar un usuario es muy sencillo. Primero debemos pulsar el bot&amp;oacute;n &quot;Usuarios&quot;
        ///				en  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
    }
}
